# Generated by Django 5.2.12 on 2026-04-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum stock level before reordering is required'),
        ),
    ]
